name: Build Mentis

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with JLink
        run: ./gradlew jlink

      - name: Build with JPackage
        run: ./gradlew jpackage

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: mentis-app
          path: build/MentisApp/bin/

      - name: Upload mac
        uses: actions/upload-artifact@v4
        with:
          name: mentis-app-mac-installer
          path: build/jpackage/MentisInstaller-1.0.0.dmg
