name: Build & Release Mentis

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'   # z. B. v1.0.0

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with JLink
        run: ./gradlew jlink

      - name: Build with JPackage
        run: ./gradlew jpackage

      # Artefakte für spätere Jobs bereitstellen
      - name: Upload jpackage artifact
        uses: actions/upload-artifact@v4
        with:
          name: jpackage-output
          path: build/jpackage/*

      - name: Upload app zip
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: build/MentisApp/*.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-14

    steps:
      - name: Download jpackage artifact
        uses: actions/download-artifact@v4
        with:
          name: jpackage-output
          path: ./release-assets

      - name: Download app zip
        uses: actions/download-artifact@v4
        with:
          name: app-zip
          path: ./release-assets

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-assets/MentisInstaller-*.dmg
          asset_name: MentisInstaller-1.0.0.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-assets/MentisApp.zip
          asset_name: MentisApp-${{ github.ref_name }}.zip
          asset_content_type: application/zip
