name: Build Mentis

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with JLink
        run: ./gradlew jlink

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: mentis-app
          path: build/jlink/
