name: Build macOS installers

on:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-14]   # Intel (x86_64) and Apple Silicon (arm64)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with JLink
        run: ./gradlew jlink

      - name: Build with JPackage
        run: ./gradlew jpackage

      - name: Upload DMG as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mentis-dmg-${{ matrix.os }}
          path: build/jpackage/*.dmg
