name: Build Mentis

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'    # Tags wie v1.0.0 triggern den Release-Workflow

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with JLink
        run: ./gradlew jlink

      - name: Build with JPackage
        run: ./gradlew jpackage

      - name: Upload zip as artifact (only on branch pushes)
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v4
        with:
          name: mentis-app
          path: build/MentisApp/

      - name: Upload mac installer as artifact (only on branch pushes)
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v4
        with:
          name: mentis-app-mac-installer
          path: build/jpackage/MentisInstaller-1.0.0.dmg

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /build/jpackage/MentisInstaller-1.0.0.dmg
          asset_name: MentisInstaller.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /build/MentisApp/MentisApp.zip
          asset_name: MentisApp.zip
          asset_content_type: application/zip
